name: Install tools

runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            6.x
            7.x
            8.0.100-rc.2.23502.2

    - name: Install .NET tools
      shell: pwsh
      run: dotnet tool restore
