namespace VisualStudio.VersionScraper.Writers.CSharp;

using SlnUp.Core;
using System.Diagnostics.CodeAnalysis;
using System.IO.Abstractions;
using Treasure.Utils;

internal class CSharpVersionWriter
{
    private const string ClassName = "VersionManager";

    private const string GetVersionsMethodName = "GetDefaultVersions";

    private const string NamespaceName = "SlnUp";

    private static IEnumerable<string> ImportNamespaces = new[]
    {
        "SlnUp.Core"
    };

    private readonly IFileSystem fileSystem;
    public CSharpVersionWriter(IFileSystem fileSystem) => this.fileSystem = Argument.NotNull(fileSystem);

    public void WriteClassToFile(IEnumerable<VisualStudioVersion> versions, string filePath)
    {
        using StreamWriter streamWriter = this.fileSystem.File.CreateText(filePath);
        CodeWriter writer = new(streamWriter);
        WriteHeader(writer);
        writer.WriteLine();
        WriteClass(writer, versions);
    }

    private static void WriteClass(CodeWriter writer, IEnumerable<VisualStudioVersion> versions)
    {
        writer.WriteLine($"namespace {NamespaceName};");
        writer.WriteLine();
        foreach (string importNamespace in ImportNamespaces)
        {
            writer.WriteLine($"using {importNamespace};");
        }
        writer.WriteLine();
        writer.WriteLine($"internal partial class {ClassName}");
        using (writer.WithBrackets())
        {
            WriteLatestVersions(writer);
            writer.WriteLine();
            WriteGetVersionsMethod(writer, versions);
        }
    }

    private static void WriteLatestVersions(CodeWriter writer)
    {
        VisualStudioProduct latestProduct = Enum.GetValues<VisualStudioProduct>().Max();
        writer.WriteLine($"public const {nameof(VisualStudioProduct)} LatestProduct = {nameof(VisualStudioProduct)}.{latestProduct};");
        writer.WriteLine();
        writer.WriteLine($"public const string LatestProductValue = \"{(int)latestProduct}\";");
    }

    [SuppressMessage("Globalization", "CA1304:Specify CultureInfo")]
    private static void WriteGetVersionsMethod(CodeWriter writer, IEnumerable<VisualStudioVersion> versions)
    {
        writer.WriteLine($"public static IReadOnlyList<{nameof(VisualStudioVersion)}> {GetVersionsMethodName}()");
        using (writer.WithBrackets())
        {
            writer.WriteLine("return new []");

            using (writer.WithBrackets(closingSemicolon: true))
            {
                foreach (VisualStudioVersion version in versions)
                {
                    writer.WriteLine($"new {nameof(VisualStudioVersion)}({nameof(VisualStudioProduct)}.{version.Product}, Version.Parse(\"{version.Version}\"), Version.Parse(\"{version.BuildVersion}\"), \"{version.Channel}\", {version.IsPreview.ToString().ToLower()}),");
                }
            }
        }
    }

    private static void WriteHeader(CodeWriter writer)
    {
        writer.WriteLine($@"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Version: {ThisAssembly.AssemblyInformationalVersion}
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------".TrimStart());
    }
}
