name: SlnUp-CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.config/**'
      - '.github/dependabot.yml'
      - '.vscode/**'
      - 'docs/**'
      - 'README.md'

jobs:
  build_ci:
    name: Build SlnUp
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      # don't check format on CI builds due to common breaking changes in the .NET SDK
      checkFormat: false

  release_ci:
    name: Release SlnUp to NuGet.org
    needs: build_ci
    if: ${{ !contains(needs.build_ci.outputs.package_version, '-') }}
    uses: ./.github/workflows/workflow_release.yml
    secrets: inherit
    with:
      package-version: ${{ needs.build_ci.outputs.package_version }}
