name: SlnUp-PR

on: pull_request

jobs:
  build_pr:
    name: Build SlnUp
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        platform: [
          { os: windows, buildAgent: windows-latest },
          { os: ubuntu, buildAgent: ubuntu-latest },
          { os: macos, buildAgent: macos-14 }
        ]
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      artifactSuffix: ${{ matrix.platform.os }}
      buildAgent: ${{ matrix.platform.buildAgent }}
