name: SlnUp-PR

on: pull_request

jobs:
  build_pr:
    name: Build SlnUp
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        platform: [ windows, ubuntu, macos ]
    uses: ./.github/workflows/workflow_build.yml
    secrets: inherit
    with:
      platform: ${{ matrix.platform }}
