name: 'SlnUp-PR'

on: pull_request

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  SETUP_DOTNET_VERSION: 6.0.102

jobs:
  build:
    name: 'Build SlnUp'
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        platform: [ windows, ubuntu, macos ]
    runs-on: ${{ matrix.platform }}-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.SETUP_DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: DotNet Format
        run: dotnet format --no-restore --verify-no-changes

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          name: codecov-${{ matrix.platform }}
          directory: __test-results
          fail_ci_if_error: true
          verbose: true

      - name: Upload output artifact
        uses: actions/upload-artifact@v2
        with:
          name: __output_${{ matrix.platform }}
          path: __output

      - name: Upload packages artifact
        uses: actions/upload-artifact@v2
        with:
          name: __packages_${{ matrix.platform }}
          path: __packages
